### ISSUE TITLE
Support webpack 5?

### ISSUE THREAD

**Issue by TSMMark** [flut1/webpack-on-demand#2]
This plugin was recommended here https://github.com/tatethurston/webpack-inject-entry-plugin/issues/1#issuecomment-1137597809

However when trying to use this with webpack 5.x it does not look compatible.

```
[18:13:04] TypeError: callback is not a function
    at /Users/mark/code/web/node_modules/enhanced-resolve/lib/Resolver.js:409:24
    at eval (eval at create (/Users/mark/code/web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /Users/mark/code/web/node_modules/enhanced-resolve/lib/Resolver.js:409:24
    at eval (eval at create (/Users/mark/code/web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/mark/code/web/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:88:10
    at /Users/mark/code/web/node_modules/enhanced-resolve/lib/Resolver.js:409:24
    at eval (eval at create (/Users/mark/code/web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at /Users/mark/code/web/node_modules/enhanced-resolve/lib/Resolver.js:409:24
    at eval (eval at create (/Users/mark/code/web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:58:1)
    at /Users/mark/code/web/node_modules/enhanced-resolve/lib/ConditionalPlugin.js:54:9
```

It's possible I'm doing something else wrong but I'm assuming it's webpack 5 compat. 

Any chance this would be updated? It looks like a really neat plugin to optimize dev webpack experience. Kind of like Vite. Nice. Thanks!

**Comment by flut1** [comment]
Hi @TSMMark ,

It surprises me that a few years after I created this, there are still people interested! I currently use Vite on many of my projects for exactly this reason.

I'm happy to have a quick look into supporting Webpack 5 soon. I won't be able to invest a great amount of time in this project, but hopefully someone else can pick up where I left off.
